### PR TITLE
GMS workaround

### PR DESCRIPTION
**Pull request by DroidFreak32**
This fixes mobile network issues on certain devices.

### CODE REVIEW

**Comment by CheckYourScreen** [comment]
I dont think its a good idea to ship libprotobuf for each and every device, specially for those which are using prebuilts.

**Comment by DroidFreak32** [comment]
Oh. Alright.. I saw this commit in tipsy that's why I pulled this request here too.

**Comment by CheckYourScreen** [comment]
Let @martinusbe decide cz I'm facing one weird issue with playstore. I'll run some tests with this commit locally.

**Comment by Martinusbe** [comment]
Devices that need it have it in devicetrees afaik on tesla & validus.
But i have no issues with merging this in common, we'll have to ask if anyone has issues with it i guess or find out after the fact ;-)

**Comment by DroidFreak32** [comment]
Right now the only device I know that faces this problem is mido. I'll just add it to the device tree instead

**Comment by Martinusbe** [comment]
also, authorship 
https://github.com/TipsyOs/vendor_tipsy/commit/3bb3523820bad4a6997e0380c824bfc76fe9ca6c
https://review.slimroms.org/#/c/23842/
https://review.lineageos.org/#/c/144697/

**Pull request closed without merging**
